from distribute_setup import use_setuptools
use_setuptools()
from setuptools import setup, find_packages

from numpy.distutils.core import setup,Extension
from distutils.sysconfig import get_python_lib
import os,sys

_readklu = Extension('_readklu', sources = ['src/readklu.cc'] )
_spikes = Extension('spikes', sources = ['src/spikes.pyf','src/spikes.c'])

setup(name = "mspikes",
      version = "2.0a1",
      packages = find_packages(),
      entry_points = {'console_scripts': ['mspike_extract = mspikes.spike_extract:main',
                                          'mspike_group = mspikes.groupevents:main']},
      
      description = """ Python scripts and modules for processing
      spike data from SABER, a data acquisition program that stores
      data in pcm_seq2 format and writes metadata to a flat 'explog'
      text file.  The spike_extract script is used to read the explog
      file and extract spike times and features from the pcm data,
      exporting to files readable by the Klusters spike-sorting
      software; the groupevents script reads sorted cluster files
      generated by Klusters and outputs toe_lis data. """,

      install_requires = ["numpy>=1.3", "scipy>=0.7", "tables>=2.1", "arf>=1.0.0"],

      maintainer = "CD Meliza",
      maintainer_email = "dmeliza@uchicago.edu",
      ext_package = 'mspikes',
      ext_modules = [ _readklu, _spikes ]
      )
